iso3s:
  - "ner"
  - "nga"
  - "cmr"
  - "tcd"
  - "bfa"
  - "eth"
  - "ssd"
  - "som"
  - "mli"
  - "cod"

adm_levels:
  - 0
  - 1
  - 2

regions:
  - adm_level: 1
    iso3: "cod"
    region_number: 1
    region_name: "Zone 1"
    pcodes:
      - "CD52"  # BASUELE1
      - "CD53"  # HAUTUELE1
      - "CD51"  # TSHOPO1

  - adm_level: 1
    iso3: "cod"
    region_number: 2
    region_name: "Zone 2"
    pcodes:
      - "CD61"  # NORDKIVU1
      - "CD62"  # SUDKIVU1

  - adm_level: 1
    iso3: "cod"
    region_number: 3
    region_name: "Zone 3"
    pcodes:
      - "CD74"  # TANGANYIKA1
